/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sigmav.view.fornecedor;

/**
 *
 * @author meritor
 */

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sigmav.entity.Contato;
import sigmav.entity.Fornecedor;
import sigmav.hibernate_jpa_entityManager.HDaoFornecedor;

public class FornCons extends javax.swing.JDialog {

    /**
     * Creates new form PecaCons
     */
    private Fornecedor fornecedor;
    //private Fornecedor fornAbas; 
    private Contato contato;
    private List<Fornecedor> listaFornecedores;
    private java.awt.Frame parent;
    private boolean modal;
    private int linha = 0;
    ArrayList<Fornecedor> listaPog;
    
    
    public FornCons(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.modal = modal;
        
        setTitle("Sigmav - Fornecedores:");
        setLocationRelativeTo(null);
        
        this.listaFornecedores = new ArrayList<Fornecedor>();
        jButtonSetLocAb.setVisible(false);
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        tablesModelis.setRowCount(0);
        
        AtualizarTabela();
    }
    
    /*
    public FornCons(java.awt.Frame parent, boolean modal, Fornecedor fornecedorExt) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.modal = modal;
        
        setTitle("Sigmav - Fornecedores:");
        setLocationRelativeTo(null);
        
        this.fornecedor = new Fornecedor();
        this.fornAbas = fornecedorExt;
        this.listaFornecedores = new ArrayList<Fornecedor>();
        jButtonSetLocAb.setVisible(false);
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        tablesModelis.setRowCount(0);
        
        AtualizarTabela();
    }
    */
    /*
    public FornCons(java.awt.Frame parent, boolean modal, Fornecedor fornecedorExt, boolean pog) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.modal = modal;
        
        setTitle("Sigmav - Fornecedores:");
        setLocationRelativeTo(null);
        
        this.fornecedor = new Fornecedor();
        this.fornAbas = fornecedorExt;
        this.listaFornecedores = new ArrayList<Fornecedor>();
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        tablesModelis.setRowCount(0);
        
        AtualizarTabela();
    }
    */
    
    //CONSULTA CHAMADA POR ABASTECIMENTO:
    public FornCons(java.awt.Frame parent, boolean modal, ArrayList<Fornecedor> fornecedorExt, boolean pog) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.modal = modal;
        
        this.listaPog = fornecedorExt;
        setTitle("Sigmav - Fornecedores:");
        setLocationRelativeTo(null);
        
        this.fornecedor = new Fornecedor();
        this.contato = this.fornecedor.getContato();
        
        this.listaFornecedores = new ArrayList<Fornecedor>();
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        tablesModelis.setRowCount(0);
        
        AtualizarTabela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldChaveDaPesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipoDePesquisa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int col) {

                return false;
            }

        };
        jButtonNovaPeca = new javax.swing.JButton();
        jButtonVisualizarPeca = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonFecharTela = new javax.swing.JButton();
        jButtonSetLocAb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 549));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisar");

        jLabel2.setText("Chave da busca:");

        jTextFieldChaveDaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChaveDaPesquisaActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquisar por:");

        jComboBoxTipoDePesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código fornecedor", "Nome", "Responsável"}));
        jComboBoxTipoDePesquisa.setToolTipText("Tipo de pesquisa");

        jTableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código fornecedor:", "Nome:", "Responsável:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableFornecedores);
        jTableFornecedores.getColumnModel().getColumn(0).setResizable(false);
        jTableFornecedores.getColumnModel().getColumn(1).setResizable(false);
        jTableFornecedores.getColumnModel().getColumn(2).setResizable(false);

        jButtonNovaPeca.setText("Adicionar");
        jButtonNovaPeca.setToolTipText("Adicionar");
        jButtonNovaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaPecaActionPerformed(evt);
            }
        });

        jButtonVisualizarPeca.setText("Visualizar");
        jButtonVisualizarPeca.setToolTipText("Visualizar");
        jButtonVisualizarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarPecaActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonFecharTela.setText("Fechar");
        jButtonFecharTela.setToolTipText("Fechar");
        jButtonFecharTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharTelaActionPerformed(evt);
            }
        });

        jButtonSetLocAb.setText("Selecionar fornecedor abastecimento");
        jButtonPesquisar.setToolTipText("Seleconar fornecedor abastecimeto");
        jButtonSetLocAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetLocAbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldChaveDaPesquisa)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTipoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonNovaPeca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVisualizarPeca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonFecharTela))
                            .addComponent(jButtonSetLocAb, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldChaveDaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSetLocAb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaPeca)
                    .addComponent(jButtonVisualizarPeca)
                    .addComponent(jButtonFecharTela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChaveDaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChaveDaPesquisaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldChaveDaPesquisaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        this.listaFornecedores = new ArrayList<Fornecedor>();
        char[] caux = jTextFieldChaveDaPesquisa.getText().trim().toCharArray();
        boolean daxus = true;
        boolean auxsPog = true;
        
        for ( int i = 0; i < caux.length; i++ ){
            //System.out.println(caux[i]);
        // verifica se o char não é um dígito  
            
            if ( !Character.isDigit( caux[ i ] ) ){
                daxus = false;
                
                break;
            }
                
        }  
    
        tablesModelis.setRowCount(0);
        
        try {
            // TODO add your handling code here:
            //this.peca = new Peca();
            if(jComboBoxTipoDePesquisa.getSelectedIndex() == 0){
               
                if(daxus == false || caux.length == 0){                    
                    JOptionPane.showMessageDialog(parent, "Busca inválida, reconfigure.", "Pesquisar", 2, null);
                    auxsPog = false;
                    
                } else{
                    this.fornecedor = new HDaoFornecedor().retrieve(Long.valueOf(jTextFieldChaveDaPesquisa.getText()));
                    
                    if(this.fornecedor != null){
                        this.listaFornecedores.add(this.fornecedor);
                    }
                    
               }
                
            } else if(jComboBoxTipoDePesquisa.getSelectedIndex() == 1){
                this.listaFornecedores =  new HDaoFornecedor().retrieveByNome(jTextFieldChaveDaPesquisa.getText());
                
            }            
            else {
                this.listaFornecedores = new HDaoFornecedor().retrieveByResponsavel(jTextFieldChaveDaPesquisa.getText());
                        
            } 
            
            if(listaFornecedores.size() > 0){
                for(Fornecedor fTemp : listaFornecedores){                    
                    tablesModelis.addRow(new Object[]{fTemp.getId(),fTemp.getNome(),fTemp.getContato().getResponsavel()});
                                        
                }
                jTableFornecedores.setRowSelectionInterval(0, 0);
            }
            
            jTableFornecedores.setModel(tablesModelis);
            
            //peca = listaPecas.get(jTextFieldChaveDaPesquisa.cocon)
            //tedBook = booksList.get(table.convertRowIndexToModel(selectedRow));
            
            //jTable1.getse
            
            
            if(tablesModelis.getRowCount() == 0 && auxsPog == true){
                JOptionPane.showMessageDialog(parent, "Nenhum fornecedor encontrado.", "Pesquisar", 2, null);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(FornCons.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonFecharTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharTelaActionPerformed
        // TODO add your handling code here:        
        dispose();
    }//GEN-LAST:event_jButtonFecharTelaActionPerformed

    private void jButtonVisualizarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarPecaActionPerformed
        // TODO add your handling code here:
        linha = jTableFornecedores.getSelectedRow();
        //System.out.println(linha+"################");
        if(linha < 0){
            // Alerta se nenhum item for selecionado
            JOptionPane.showMessageDialog(parent, "Selecione um item da lista.", "Visualizar", 2, null);
        } else{
            this.fornecedor = this.listaFornecedores.get(linha);            
            VisualizarFornecedor();            
            AtualizarTabela();
        }
                
    }//GEN-LAST:event_jButtonVisualizarPecaActionPerformed

    private void jButtonNovaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaPecaActionPerformed
        // TODO add your handling code here:        
        NovoCadastroFornecedor();
        
        if(this.fornecedor.getId() >= 1){
            VisualizarFornecedor();
        }        
        
        AtualizarTabela();        
    }//GEN-LAST:event_jButtonNovaPecaActionPerformed

    private void jButtonSetLocAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetLocAbActionPerformed
        // TODO add your handling code here:
        linha = jTableFornecedores.getSelectedRow();
        //System.out.println(linha+"################");
        if(linha < 0){
            // Alerta se nenhum item for selecionado
            JOptionPane.showMessageDialog(parent, "Selecione um item da lista.", "Visualizar", 2, null);
        } else{
            this.fornecedor = this.listaFornecedores.get(linha);                      
        }
        
        this.listaPog.add(this.fornecedor);
        
        dispose();
    }//GEN-LAST:event_jButtonSetLocAbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornCons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FornCons dialog = new FornCons(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //##########################################################################
    
    private void AtualizarTabela(){
        
        DefaultTableModel tablesModelis = (DefaultTableModel) jTableFornecedores.getModel();
        this.listaFornecedores = new ArrayList<Fornecedor>();
    
        tablesModelis.setRowCount(0);

        this.listaFornecedores = new HDaoFornecedor().retrieveByResponsavel("");

        if(listaFornecedores.size() > 0){
            for(Fornecedor fTemp : listaFornecedores){                    
                tablesModelis.addRow(new Object[]{fTemp.getId(),fTemp.getNome(),fTemp.getContato().getResponsavel()});
                                    
            }
            jTableFornecedores.setRowSelectionInterval(0, 0);
        } else {
            JOptionPane.showMessageDialog(parent, "Não existem fornecedores cadastrados atualmente.", "Fornecedores", 2, null);
        }
        
        jTableFornecedores.setModel(tablesModelis);
         
    }
    
    private void NovoCadastroFornecedor(){
        this.fornecedor = new Fornecedor();
    
        int flagPOG = 2;
        FornCad tFornCad = new FornCad(this.parent, this.modal, this.fornecedor, flagPOG);
        tFornCad.setLocationRelativeTo(this);
        tFornCad.setResizable(false);
        tFornCad.setVisible(true);
        
    }
    
    private void VisualizarFornecedor(){
        FornVis tFornVis = new FornVis(this.parent, this.modal,this.fornecedor);
        tFornVis.setLocationRelativeTo(this);
        tFornVis.setResizable(false);
        tFornVis.setVisible(true);
               
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharTela;
    private javax.swing.JButton jButtonNovaPeca;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSetLocAb;
    private javax.swing.JButton jButtonVisualizarPeca;
    private javax.swing.JComboBox jComboBoxTipoDePesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedores;
    private javax.swing.JTextField jTextFieldChaveDaPesquisa;
    // End of variables declaration//GEN-END:variables
}
